version: "3.8"
services:
  postgres:
    image: "postgres:14.5"
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: "div"
      POSTGRES_PASSWORD: "divpassword"
      POSTGRES_DB: "divdata"
